package org.canvas.publication.asset;

import java.util.Arrays;
import java.util.Objects;
import java.util.UUID;

public interface AudioGenerator {
    default String cacheNamespace() {
        return "placeholder-audio-v1";
    }

    GeneratedBinary generate(ApprovedDescriptionInput input);

    record ApprovedDescriptionInput(UUID revisionId, String label, String text) {
        public ApprovedDescriptionInput {
            Objects.requireNonNull(revisionId, "revisionId");
            Objects.requireNonNull(label, "label");
            Objects.requireNonNull(text, "text");
        }
    }

    record GeneratedBinary(byte[] bytes, String mediaType, String generator) {
        public GeneratedBinary {
            bytes = Arrays.copyOf(Objects.requireNonNull(bytes, "bytes"), bytes.length);
            if (bytes.length == 0) throw new IllegalArgumentException("Generated bytes must not be empty.");
            Objects.requireNonNull(mediaType, "mediaType");
            Objects.requireNonNull(generator, "generator");
        }

        @Override
        public byte[] bytes() {
            return Arrays.copyOf(bytes, bytes.length);
        }
    }
}
